MemberEmployee/Models/Entities/Member.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MemberEmployee.Models.Entities
{
    public class Member
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; } 
        public DateTime DateOfBirth { get; set; }
        
        public int? MemberId { get; set; }
        // Navigation property for one-to-one relationship
        public Employee Employee { get; set; }  // This defines the relationship with Employee
    }
}

MemberEmployee/Controllers/MembersController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MemberEmployee.Models.Data;
using MemberEmployee.Models.Entities;
using Rotativa;

namespace MemberEmployee.Controllers
{
    public class MembersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext(); //Interact with database

        // GET: Members
        public ActionResult Index()
        {
            // Ensure the Employee data is included when retrieving Members
            var members = db.Members.Include(m => m.Employee).ToList();
            return View(members);
        }


        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            ViewBag.Members = new SelectList(db.Members, "Id", "Name");
            return View();
        }

        // POST: Members/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Email,DateOfBirth")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email,DateOfBirth")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //for filtering 
        public ActionResult FilterBySalary(decimal? minSalary, decimal? maxSalary)
        {
            if (minSalary == null || maxSalary == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var filteredMembers = db.Members
                .Include("Employee") // Ensures Employee is loaded with Member
                .Where(m => m.Employee != null &&
                            m.Employee.Salary >= minSalary &&
                            m.Employee.Salary <= maxSalary)
                .ToList();

            return View("FilterBySalary", filteredMembers); 
        }

        //for printing members details

        public ActionResult PrintDetails()
        {
            var members = db.Members.Include(m => m.Employee).ToList(); // Load related Employee data
            return View(members); // Render the view with the members' data
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MemberEmployee/Views/Members/Create.cshtml
@model MemberEmployee.Models.Entities.Member

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MemberEmployee/Views/Members/Delete.cshtml
@model MemberEmployee.Models.Entities.Member

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MemberEmployee/Views/Members/Details.cshtml
@model MemberEmployee.Models.Entities.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MemberEmployee/Views/Members/Edit.cshtml
@model MemberEmployee.Models.Entities.Member

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MemberEmployee/Views/Members/FilterBySalary.cshtml
@model IEnumerable<MemberEmployee.Models.Entities.Member>
@{
    ViewBag.Title = "FilterBy                                                                                                                                                                                                                                                   Salary";
}

<h2>FilterBySalary</h2>

<<table class="table">
    <thead>
        <tr>
            <th>Member Name</th>
            <th>Email</th>
            <th>Date of Birth</th>
            <th>Salary</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var member in Model)
        {
            <tr>
                <td>@member.Name</td>
                <td>@member.Email</td>
                <td>@member.DateOfBirth.ToString("dd/MM/yyyy")</td>
                <td>
                    @if (member.Employee != null)
                    {
                        @member.Employee.Salary.ToString("C") <!-- Format salary as currency -->
                    }
                    else
                    {
                        <span>No Employee</span>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

MemberEmployee/Views/Members/Index.cshtml
@model IEnumerable<MemberEmployee.Models.Entities.Member>


@{
    ViewBag.Title = "Index";
}
@{
    ViewBag.Title = "Filter Members by Salary";
}

<h2>Filter Members by Salary</h2>

@using (Html.BeginForm("FilterBySalary", "Members", FormMethod.Get))
{
    <div class="form-group">
        <label for="minSalary">Minimum Salary:</label>
        <input type="number"
               name="minSalary"
               class="form-control"
               placeholder="Enter minimum salary"
               step="0.01"
               required />
    </div>
    <div class="form-group">
        <label for="maxSalary">Maximum Salary:</label>
        <input type="number"
               name="maxSalary"
               class="form-control"
               placeholder="Enter maximum salary"
               step="0.01"
               required />
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
}

<h2>Index</h2>


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Position
        </th>
        <th>
            Salary
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @(item.Employee != null ? item.Employee.Position : "N/A")
            </td>
            <td>
                @(item.Employee != null ? item.Employee.Salary : 0.00m)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<a href="@Url.Action("PrintDetails", "Members")" class="btn btn-primary">Print Member Details</a>

MemberEmployee/Views/Members/PrintDetails.cshtml
@Model IEnumerable<MemberEmployee.Model.Entities.Member>
    @{
        ViewBag.Title = "PrintDetails";
    }

    <!DOCTYPE html>
    <html>
    <head>
        <title>Member Details</title>
        <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
     

        </style>
    </head>
    <body>
        <h1>Member and Employee Details</h1>
        <table>
            <thead>
                <tr>
                    <th>Member Name</th>
                    <th>Email</th>
                    <th>Date of Birth</th>
                    <th>Employee Position</th>
                    <th>Salary</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var member in Model)
                {
                    <tr>
                        <td>@member.Name</td>
                        <td>@member.Email</td>
                        <td>@member.DateOfBirth.ToString("dd/MM/yyyy")</td>
                        <td>@(member.Employee != null ? member.Employee.Position : "N/A")</td>
                        <td>@(member.Employee != null ? member.Employee.Salary.ToString("C") : "N/A")</td>
                    </tr>
                }
            </tbody>
        </table>

        <button class="no-print" onclick="window.print()">Print</button>
    </body>
</html>